# Generated by Django 5.2.7 on 2025-11-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=dict, help_text="Multiple choice options: {'A': 'option1', 'B': 'option2', etc.}"),
        ),
    ]
