# Generated by Django 5.2.7 on 2025-11-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_question_type_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Quiz duration in minutes'),
        ),
        migrations.CreateModel(
            name='QuizQuestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unattempted', 'Unattempted'), ('attempted', 'Attempted'), ('marked_for_review', 'Marked for Review'), ('answered_and_marked', 'Answered and Marked for Review')], default='unattempted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_statuses', to='quiz.quiz')),
            ],
            options={
                'ordering': ['quiz', 'question'],
                'unique_together': {('quiz', 'question')},
            },
        ),
    ]
